### ISSUE TITLE
Not receiving typing event neither in NexmoMessageEventListener nor in NexmoTypingEventListener

### ISSUE THREAD

**Issue by GowthamGnanajothi** [nexmo-community/client-sdk-android-tutorial-messaging-java#1] opened 2021-04-12 07:24 UTC
Hi,

I am not receiving any typing event when other member is typing. 

I have use case to show when other member is typing in my mobile. 
**Tested scenario - Member events, Text events, Custom events are sent and received successfully**

- From (mobile to web browser) - web-platform is receiving the typing event posted by mobile  
- From (web browser to mobile) - mobile-platform is not receiving the typing event posted by web. [tested on both android and iOS platform]

To cross verify whether it is platform specific (used the same code as in this repo with config and code changes to handle type event)
**Tested scenario - Member events, Text events, Custom events are sent and received successfully**

- From (mobile to mobile) - Not receiving the typing event in both sides. [tested on android]

Followed the same code snippets as in guide for Typing indicators - ref - https://developer.nexmo.com/client-sdk/in-app-messaging/guides/typing-indicators/java

### **Implementaion information:**
Posted typing events with conversation.startTyping() and conversation.stopTyping()
Expected to receive typing events as part of NexmoMessageEventListener - onTypingEvent() also tried with NexmoTypingEventListener

Any help or pointers if I am missing something would be helpful. @igorwojda 

Thanks,
Gowtham G

**Comment by igorwojda** [comment] 2021-06-10 17:26
Hey, it looks like this is a bug in the SDK.

**Comment by igorwojda** [comment] 2021-06-18 06:01
This bug is confirmed. 
Android SDK 3.0.1 with a hotfix already have been released.
iOS SDJ with hotfix will be released around EOF Q2.

**Closed as completed by igorwojda** 2021-06-18 06:01 UTC
